# Generated by Django 5.1.6 on 2025-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carted',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
