# Generated by Django 5.1.6 on 2025-05-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_invoice_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order'),
        ),
    ]
